# py-ot_planning/mensajes.py

TEXTOS = {
    "TITULO_APP": "Planificador de OT",
    "TABLA_CODIGO": "Codigo",
    "TABLA_CATEGORIA": "Categoria",
    "TABLA_DESC": "Descripcion",
    "TABLA_PORC": "%",
    "TABLA_CANT": "Cantidad",
    "TABLA_PRECIO_U": "Precio Unitario",
    "TABLA_TOTAL": "Precio Total",
    "BOTON_AGREGAR": "Agregar Entrada",
    "ALERT_EXITO": "Entrada agregada exitosamente!",
    "ALERT_ERROR": "Error: Valores ingresados no válidos.",
    "FORM_NUEVO": "Nueva Entrada",
    "ALERT_ERROR_LOGIN": "Usuario o contraseña inválidos",
    "HOME": "Inicio",
    "CLIENTES": "Clientes", 
    "AGENDAMIENTOS": "Agendamientos",
    "FACTURACION": "Facturación",
    "AJUSTES": "Ajustes",  
    "LOGOUT": "Cerrar Sesión",
    "SALIR": "Salir",
    "AJUSTES_TITULO": "Gestión de Usuarios",
    "TABLA_USUARIO": "Nombre de Usuario",
    "ACCIONES": "Acciones",
    "BOTON_NUEVO_USUARIO": "Crear Usuario",
    "BOTON_ELIMINAR": "Eliminar",
    "CONFIRMAR_ELIMINAR": "¿Está seguro de eliminar este usuario?",
    "ALERT_USER_CREADO": "Usuario creado exitosamente.",
    "ALERT_USER_ELIMINADO": "Usuario removido del sistema.",
    "BOTON_MODIFICAR": "Modificar",
    "MODIFICAR_TITULO": "Actualizar Perfil",
    "MODIFICAR_INFO": "Deje la contraseña en blanco para mantener la actual.",
    "ALERT_USER_ACTUALIZADO": "Datos actualizados correctamente.",
    "ERROR_PERMISO": "No tiene permiso para editar este perfil.",
    "CLIENTES_TITULO": "Registro de Clientes y Proveedores",
    "TABLA_TIPO": "Tipo de Entidad",
    "TIPO_CLIENTE": "Cliente Final",
    "TIPO_QUIMICOS": "Proveedor: Químicos Piscina",
    "TIPO_VIVERO": "Vivero (Plantas/Árboles)",
    "TIPO_PAISAJISMO": "Paisajismo (Piedras/Deco)",
    "TIPO_MACETAS": "Macetas",
    "TIPO_JARDINES": "Mantenimiento/Limpieza",
    "BOTON_NUEVO_CLIENTE": "Agregar Registro",
    "AGENDAMIENTOS": "Agendamientos",

}

TEXTOS.update({
    "TIPO_CONTRATO": "Tipo de Contrato",
    "CONTRATO_PISCINA": "Solo Piscina",
    "CONTRATO_JARDIN": "Solo Jardín",
    "CONTRATO_AMBOS": "Piscina y Jardín",
    "CONTRATO_PROVEEDOR": "Proveedores",
    "STATUS_ACTIVO": "Activo",
    "STATUS_SUSPENDIDO": "Suspendido",
    "UBICACIONES": "Ubicaciones / Maps",
    "CONOCIMIENTO_CLIENTE": "Conocimiento Detallado del Cliente",
    "AYUDA_OBSERVACIONES": "Horarios, facturación, persona de contacto, condiciones de pago..."
})

