"""columna servicio

Revision ID: 0c56fd9eef87
Revises: d4c78701fa12
Create Date: 2026-04-14 20:04:10.291962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c56fd9eef87'
down_revision = 'd4c78701fa12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicio', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('servicio')

    # ### end Alembic commands ###
