"""agregar columnas telefono email a cliente

Revision ID: 440493ea4ede
Revises: 7200e5b81648
Create Date: 2026-04-11 18:14:05.329722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440493ea4ede'
down_revision = '7200e5b81648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
