"""observacion field

Revision ID: 46903a904be6
Revises: b7ed125e62ab
Create Date: 2026-04-17 13:36:43.024183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46903a904be6'
down_revision = 'b7ed125e62ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###
