"""inicial base datos

Revision ID: 595cd15b5faa
Revises: 
Create Date: 2026-04-10 18:32:19.159661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595cd15b5faa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('percentage', sa.String(length=5), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_entry')
    # ### end Alembic commands ###
