"""incializar tabla categorias

Revision ID: 7200e5b81648
Revises: d09cc71854b4
Create Date: 2026-04-11 16:50:29.797833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7200e5b81648'
down_revision = 'd09cc71854b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_categoria_nombre'), ['nombre'])

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cliente_categoria_id_categoria'), 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cliente_categoria_id_categoria'), type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_categoria_nombre'), type_='unique')

    # ### end Alembic commands ###
