"""frecuencia de visita

Revision ID: 818551e7f1cf
Revises: efe28cdb842d
Create Date: 2026-04-17 12:36:43.394885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818551e7f1cf'
down_revision = 'efe28cdb842d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurrencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segundo_dia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_generado', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurrencias', schema=None) as batch_op:
        batch_op.drop_column('ultimo_generado')
        batch_op.drop_column('segundo_dia')

    # ### end Alembic commands ###
