"""se agrega col admin como atributo de user

Revision ID: 98b12b252619
Revises: 33a511d85f07
Create Date: 2026-04-11 14:29:15.729389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b12b252619'
down_revision = '33a511d85f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.create_table('planning_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('percentage', sa.VARCHAR(length=5), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit_price', sa.FLOAT(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
