"""backref from visitas

Revision ID: a6b8506fe128
Revises: f919f609cebe
Create Date: 2026-04-17 20:52:22.870084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b8506fe128'
down_revision = 'f919f609cebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_visita', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###
