"""feriados admin

Revision ID: b7ed125e62ab
Revises: 818551e7f1cf
Create Date: 2026-04-17 12:59:46.509920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ed125e62ab'
down_revision = '818551e7f1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feriado')),
    sa.UniqueConstraint('fecha', name=op.f('uq_feriado_fecha'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feriado')
    # ### end Alembic commands ###
