"""agregar categoria como columna

Revision ID: bef9b708c872
Revises: 595cd15b5faa
Create Date: 2026-04-10 18:50:49.139188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef9b708c872'
down_revision = '595cd15b5faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning_entry', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
