"""detalle de facturacion

Revision ID: c889f33eb555
Revises: 46903a904be6
Create Date: 2026-04-17 19:26:02.556813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c889f33eb555'
down_revision = '46903a904be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name=op.f('fk_detalle_visita_visita_id_visitas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_visita'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_visita')
    # ### end Alembic commands ###
