"""dev initialize

Revision ID: c9ae685a406c
Revises: 
Create Date: 2026-05-02 17:32:53.018894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ae685a406c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('nombre', name=op.f('uq_categoria_nombre'))
    )
    op.create_table('feriado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('no_laboral', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feriado')),
    sa.UniqueConstraint('fecha', name=op.f('uq_feriado_fecha'))
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('es_conductor', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sueldo_base', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_personal'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=True),
    sa.Column('chapa', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehiculo')),
    sa.UniqueConstraint('chapa', name=op.f('uq_vehiculo_chapa'))
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('tipo_entidad', sa.String(length=50), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observaciones_detalladas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('fk_cliente_categoria_id_categoria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente'))
    )
    op.create_table('configuracion_cuadrilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cuadrilla', sa.String(length=50), nullable=True),
    sa.Column('vehiculo_default_id', sa.Integer(), nullable=True),
    sa.Column('color_identificador', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_default_id'], ['vehiculo.id'], name=op.f('fk_configuracion_cuadrilla_vehiculo_default_id_vehiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracion_cuadrilla')),
    sa.UniqueConstraint('nombre_cuadrilla', name=op.f('uq_configuracion_cuadrilla_nombre_cuadrilla'))
    )
    op.create_table('miembros_cuadrilla',
    sa.Column('configuracion_cuadrilla_id', sa.Integer(), nullable=False),
    sa.Column('personal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['configuracion_cuadrilla_id'], ['configuracion_cuadrilla.id'], name=op.f('fk_miembros_cuadrilla_configuracion_cuadrilla_id_configuracion_cuadrilla')),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], name=op.f('fk_miembros_cuadrilla_personal_id_personal')),
    sa.PrimaryKeyConstraint('configuracion_cuadrilla_id', 'personal_id', name=op.f('pk_miembros_cuadrilla'))
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_sucursal', sa.String(length=100), nullable=True),
    sa.Column('coordenadas_url', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('calle_principal', sa.String(length=100), nullable=True),
    sa.Column('calle_secundaria', sa.String(length=100), nullable=True),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('grupo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_ubicacion_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ubicacion'))
    )
    op.create_table('recurrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('servicio', sa.String(length=50), nullable=True),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('segundo_dia', sa.Integer(), nullable=True),
    sa.Column('ultimo_generado', sa.Date(), nullable=True),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('hora_sugerida', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_recurrencias_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['cuadrilla_id'], ['configuracion_cuadrilla.id'], name=op.f('fk_recurrencias_cuadrilla_id_configuracion_cuadrilla')),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], name=op.f('fk_recurrencias_ubicacion_id_ubicacion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrencias'))
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cuadrilla', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('servicio', sa.String(length=100), nullable=True),
    sa.Column('hora_sugerida', sa.Time(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('recurrencia_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_visitas_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['recurrencia_id'], ['recurrencias.id'], name=op.f('fk_visitas_recurrencia_id_recurrencias')),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], name=op.f('fk_visitas_ubicacion_id_ubicacion')),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name=op.f('fk_visitas_vehiculo_id_vehiculo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitas'))
    )
    op.create_table('detalle_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visita_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('dummy', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], name=op.f('fk_detalle_visita_visita_id_visitas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_visita'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_visita')
    op.drop_table('visitas')
    op.drop_table('recurrencias')
    op.drop_table('ubicacion')
    op.drop_table('miembros_cuadrilla')
    op.drop_table('configuracion_cuadrilla')
    op.drop_table('cliente')
    op.drop_table('vehiculo')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('personal')
    op.drop_table('feriado')
    op.drop_table('categoria')
    # ### end Alembic commands ###
