"""tabla de clientes

Revision ID: d09cc71854b4
Revises: 98b12b252619
Create Date: 2026-04-11 15:26:38.916280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09cc71854b4'
down_revision = '98b12b252619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=True),
    sa.Column('ruc', sa.String(length=20), nullable=True),
    sa.Column('tipo_entidad', sa.String(length=50), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observaciones_detalladas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nombre_sucursal', sa.String(length=100), nullable=True),
    sa.Column('coordenadas_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ubicacion')
    op.drop_table('cliente')
    # ### end Alembic commands ###
