"""agendamientos, recurrencias

Revision ID: d4c78701fa12
Revises: 440493ea4ede
Create Date: 2026-04-14 12:20:20.633777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c78701fa12'
down_revision = '440493ea4ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion_id', sa.Integer(), nullable=False),
    sa.Column('servicio', sa.String(length=50), nullable=True),
    sa.Column('frecuencia', sa.String(length=20), nullable=True),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('cuadrilla_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_recurrencias_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], name=op.f('fk_recurrencias_ubicacion_id_ubicacion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrencias'))
    )
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cuadrilla', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('recurrencia_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_visitas_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['recurrencia_id'], ['recurrencias.id'], name=op.f('fk_visitas_recurrencia_id_recurrencias')),
    sa.ForeignKeyConstraint(['ubicacion_id'], ['ubicacion.id'], name=op.f('fk_visitas_ubicacion_id_ubicacion')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitas')
    op.drop_table('recurrencias')
    # ### end Alembic commands ###
