"""cuadrilla in visitas as fk

Revision ID: e9b1efa0425d
Revises: c9ae685a406c
Create Date: 2026-05-07 23:40:17.893362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b1efa0425d'
down_revision = 'c9ae685a406c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuadrilla_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_visitas_cuadrilla_id_configuracion_cuadrilla'), 'configuracion_cuadrilla', ['cuadrilla_id'], ['id'])
        batch_op.drop_column('cuadrilla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuadrilla', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_visitas_cuadrilla_id_configuracion_cuadrilla'), type_='foreignkey')
        batch_op.drop_column('cuadrilla_id')

    # ### end Alembic commands ###
