"""columnas de hora para visita

Revision ID: efe28cdb842d
Revises: 0c56fd9eef87
Create Date: 2026-04-15 12:25:49.291734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe28cdb842d'
down_revision = '0c56fd9eef87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurrencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_sugerida', sa.Time(), nullable=True))

    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_sugerida', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitas', schema=None) as batch_op:
        batch_op.drop_column('hora_sugerida')

    with op.batch_alter_table('recurrencias', schema=None) as batch_op:
        batch_op.drop_column('hora_sugerida')

    # ### end Alembic commands ###
