"""fechas para facturacion

Revision ID: f919f609cebe
Revises: c889f33eb555
Create Date: 2026-04-17 20:38:33.822506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f919f609cebe'
down_revision = 'c889f33eb555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_visita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_finished', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalle_visita', schema=None) as batch_op:
        batch_op.drop_column('date_finished')
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
